#!/usr/bin/env node
// Generates src/abi.ts from the compiled contract artifacts.
//
// The functions come from SyntheticVault and PushOracle. The errors come from every contract of
// ours, and that distinction was learned the hard way twice.
//
// First: hand-writing the error list got the stale-price error's name wrong — it is `StalePrice`,
// not `PriceStale`. viem decodes a revert only against an ABI that declares it, so a wrong name
// does not fail loudly; the revert arrives as opaque hex and the keeper cannot tell "the oracle is
// stale" from "this position is healthy".
//
// Second: taking the errors from SyntheticVault alone was still not enough. Solidity omits from a
// contract's ABI any error thrown inside an external call, and `StalePrice` is raised by the oracle
// and merely propagated by the vault. The keeper met it on its first live run as an undecodable
// 0xaffad796 and correctly refused to guess. A `liquidate` call passes through the vault, the
// oracle and the liquidity vault, so decoding needs all of their errors.
import {readFileSync, readdirSync, statSync, writeFileSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "out");
const output = join(here, "..", "src", "abi.ts");

const VAULT_FUNCTIONS = [
  "nextTokenId",
  "ownerOf",
  "liquidate",
  "liquidationThresholdBps",
  "liquidationRewardBps",
  "positions",
  "enabledFeeds",
  "assetConfig",
];

const ORACLE_FUNCTIONS = ["pushMany", "push", "lastPublishTime", "getPrice"];

function artifacts(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) return artifacts(path);
    return path.endsWith(".json") ? [path] : [];
  });
}

function read(path) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

let vaultAbi = null;
let oracleAbi = null;
const errors = new Map();
const sources = new Set();

for (const path of artifacts(out)) {
  const json = read(path);
  if (!json || !Array.isArray(json.abi)) continue;

  const target = json.metadata?.settings?.compilationTarget;
  const source = target ? Object.keys(target)[0] : null;

  // Ours only. forge-std and the test contracts declare errors that can never reach a live call,
  // and carrying them makes a name collision more likely rather than less.
  if (!source || !source.startsWith("src/") || source.includes(".t.sol")) continue;

  if (source === "src/SyntheticVault.sol") vaultAbi = json.abi;
  if (source === "src/oracle/PushOracle.sol") oracleAbi = json.abi;

  for (const entry of json.abi) {
    if (entry.type !== "error") continue;
    const signature = `${entry.name}(${entry.inputs.map((input) => input.type).join(",")})`;
    if (!errors.has(signature)) {
      errors.set(signature, entry);
      sources.add(source);
    }
  }
}

function pick(abi, names, contract) {
  if (abi === null) {
    console.error(`No ${contract} artifact under ${out}. Run \`forge build\` first.`);
    process.exit(1);
  }
  const chosen = abi.filter((entry) => entry.type === "function" && names.includes(entry.name));
  const missing = names.filter((name) => !chosen.some((entry) => entry.name === name));
  if (missing.length > 0) {
    console.error(`${contract} no longer has: ${missing.join(", ")}`);
    process.exit(1);
  }
  return chosen;
}

const vaultFunctions = pick(vaultAbi, VAULT_FUNCTIONS, "SyntheticVault");
const oracleFunctions = pick(oracleAbi, ORACLE_FUNCTIONS, "PushOracle");

// Without these the keeper cannot classify its two most important outcomes, so their absence is a
// build failure rather than something to discover in production.
const REQUIRED_ERRORS = ["PositionHealthy", "StalePrice", "UnknownPosition"];
const absent = REQUIRED_ERRORS.filter(
  (name) => ![...errors.values()].some((entry) => entry.name === name),
);
if (absent.length > 0) {
  console.error(`No artifact declares: ${absent.join(", ")}. The keeper cannot classify reverts.`);
  process.exit(1);
}

const errorList = [...errors.values()];

const body = `// Generated by scripts/gen-abi.mjs from the compiled contract artifacts. Do not edit.
//
// Functions from SyntheticVault and PushOracle; errors from every contract of ours. Solidity omits
// from a contract's ABI any error thrown inside an external call — StalePrice is raised by the
// oracle and only propagated by the vault — and viem decodes a revert solely against the ABI it is
// given. Both ABIs therefore carry the full error set.
const ERRORS = ${JSON.stringify(errorList, null, 2)} as const;

export const VAULT_ABI = [...${JSON.stringify(vaultFunctions, null, 2)}, ...ERRORS] as const;

export const ORACLE_ABI = [...${JSON.stringify(oracleFunctions, null, 2)}, ...ERRORS] as const;
`;

writeFileSync(output, body);
console.log(
  `src/abi.ts: ${vaultFunctions.length} vault functions, ${oracleFunctions.length} oracle ` +
    `functions, ${errors.size} errors from ${sources.size} contracts`,
);
